language: python
python: '3.6'
install: skip
script: skip
jobs:
  include:
    stage: Deploy to Production
    deploy:
      provider: lambda
      function_name: wittallen-net
      region: us-east-1
      role: arn:aws:iam::717333365084:role/service-role/wittallen-net-role-sm6fn87h
      runtime: python3.7
      handler_name: lambda_function.lambda_handler
      access_key_id: AKIA2OBDGQFOK5EBOHLZ
      secret_access_key:
        secure: Yevf4A6ly4V2RNXfQpAOz+x8gZI2ujy6piBJ9DyPw4m41VUZMMVFb/2eOSyr0+P693Wtsj6JwEUlz/Aw3tQMUh3WLs6CvSCOClIYu3L4AER8PT7rwXKJrMSndBMr4mqIDk71sfghGyPMGq8z3bfNJMALejrY2CBnURkrQnjZD7f0Orzy/CM2p8TSpg1G9bqqPxjY/yuvoQzlKWMXqyXrnD5sFA44D3/6113NyPSZ7NAEiKoVRkyGxi6HcT0pqt4uIpKH5OMWK9CTTRIWPLjtKtRWgSH7rTP9IKk7bdri3RSQyIic/xdaiwCnb+kwNmZZ31Nl9Xg4qX/InISlGNFAegjCUU7Iryrs77RPvAvTpOHN2IE0VuB+YRE2wysmCC3Kr7ksJ+4Ej3WrHS85FTvcSllxjnLiS3c2VSzaqChvqK6xHcEVJLnNrJkH2mHPZZBMyA2lbZ5myzvtcoOIgi4nUmQNSysqp/BKfzADKPWs0J3m6Zs09Uq8LswauNXcq/Lsem/AoghcY/ameGltgXFew9XDGxbyjAxmt9BMJU0BeJLV9yFfoSwfby9Tun5E389bQjjF/bkLai52P3PiengjVzIjanxBD8wgdW7PUc/661VRhFMD5wPOkKb71yyp1H1Ts6NwatjQWTfvzjd5cWn1j+Qu3w0/ZejTKzb7Me7QO6Q=
      on:
        all_branches: true
  
