language: python
python: '3.6'
install: skip
script: skip
jobs:
  include:
    stage: Deploy to Production
    deploy:
      provider: lambda
      function_name: wittallen-net
      region: us-east-1
      role: arn:aws:iam::717333365084:role/Travis-CI-Lambda-Deploy
      runtime: python3.7
      handler_name: lambda_function.lambda_handler
      access_key_id: AKIA2OBDGQFOFER75CNJ
      secret_access_key:
        secure: bvYQysKFmDEnzdU+51Gn3qLCTJlkRUVnV4H+1VqZ0PeFNcXOYBNAoKFq9nxzl3AtO/ZTr9ZjwR5JOEA1oN7hAch3eEQ7hcumkEFzuW3XLAP3U4HllaSEvzOyHFumbNZJQIgTUH9mWXZCTCh4Ol/UJaEZdIjUcbmabwxkcSLQyULLWeer61itle4gggJMGyAXP4aDYArJoST9Vqc4Fq8oYIX2dPvwBPtJ4qNHZALG9iiF91VW/YQkz+mAYaquU2Wkp0pGBusPSuegzTlmR9CApN4Ia3/ciBKeLD+E4JRtGBr4E3ubQMEJzA1qq9tnEj2RonLel6CzQhdbgwDDV3H1VLjpJcc8CsoWcnN6ELj2cexu2UZDLt1fVLr0RV4WqmEc53FJ/bFuMc+dbF4ROpz/Ec1DueLcK+BMDYjNW7cDQ4X8vq4iczFfjFHJaIaoFDwVVH3Ve8v0F4B3DTsVtFlaDUDPy8SAjrykWuawtSO0xbXLUA1MQ3ZKEySqEm0JJcxneWPf0SqtidswSHaGnaa6ST1HIMlnD43dQOreSnfj1mFl004m1FshCN6YDG4/UcvYW4lNoly9j9zAHGOXdZSMRGTnCtXbWAXv1ZqP7W3Q1nuIZOjsrw5FS8Au3s6owsuF4Ey9utm748eNIo62bZyhROf4IMkdRN068giUn1/s9i8=
      on:
        all_branches: true

